Repository theforeman/puppet-dns, pull requests merged in 2019-07, with the labels that each got.

#143 Allow setting service restart command
  manifests/init.pp
  manifests/params.pp
  manifests/service.pp
  spec/classes/dns_init_spec.rb
Labels: Needs testing

#144 Validate named.conf and zones.conf using named-checkconf
  manifests/config.pp
  manifests/params.pp
  manifests/view.pp
  spec/classes/dns_init_spec.rb
Labels: Enhancement, Needs testing

#148 Release 6.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed
