Repository theforeman/puppet-dns, pull requests merged in 2019-11, with the labels that each got.

#150 Update GHCG gem and drop rdoc
  Gemfile
Labels: Needs testing, Not yet reviewed

#149 Add manage_service parameter
  manifests/init.pp
  manifests/key.pp
  manifests/params.pp
  manifests/service.pp
  manifests/view.pp
  manifests/zone.pp
  spec/classes/dns_init_spec.rb
  spec/defines/dns_zone_spec.rb
Labels: Needs testing

#152 Test on CentOS 6 instead of CentOS 7
  .sync.yml
  .travis.yml
Labels: Needs testing, Not yet reviewed

#151 Refactor soaip in dns::zone
  manifests/zone.pp
  spec/acceptance/dns_spec.rb
  spec/acceptance/views_spec.rb
  spec/classes/dns_init_spec.rb
  spec/defines/dns_key_spec.rb
  spec/defines/dns_view_spec.rb
  spec/defines/dns_zone_spec.rb
  templates/zone.header.erb
Labels: Backwards incompatible, Needs testing, Not yet reviewed
