Repository theforeman/puppet-dns, pull requests merged in 2021-07, with the labels that each got.

#192 Bump version to 9.0.0
  metadata.json
Labels: Needs testing, Not yet reviewed

#191 Drop Puppet 5 support
  metadata.json
Labels: Backwards incompatible, Needs testing

#175 Replace get_in_addr_arpa with reverse_dns function
  lib/puppet/functions/dns/reverse_dns.rb
  lib/puppet/functions/get_in_addr_arpa.rb
  lib/puppet/parser/functions/get_in_addr_arpa.rb
  spec/functions/reverse_dns_spec.rb
Labels: Enhancement, Needs testing

#193 Drop EL6 and Debian 8 and Ubuntu 16.04 support
  metadata.json
Labels: Backwards incompatible, Enhancement, Needs re-review, Needs testing

#194 Release 9.0.0
  CHANGELOG.md
Labels: Needs testing

#195 Move static parameters to init.pp
  manifests/init.pp
  manifests/params.pp
Labels: Enhancement, Needs testing, Not yet reviewed
