Repository theforeman/puppet-dns, pull requests merged in 2023-11, with the labels that each got.

#240 Update gems to support testing Puppet 8
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  Gemfile
  spec/spec_helper_acceptance.rb
Labels: Not yet reviewed, Modulesync

#242 Add Debian 12 support
  manifests/params.pp
  metadata.json
  spec/classes/dns_init_spec.rb
Labels: Enhancement

#241 Release 10.2.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
